CONTROLLER_HEART_BEAT_EXPIRATION = 30
WORKER_HEART_BEAT_INTERVAL = 15

LOGDIR = "."

# Model Constants
IGNORE_INDEX = -100
IMAGE_TOKEN_INDEX = -200
AUDIO_TOKEN_INDEX = -200
DEFAULT_IMAGE_TOKEN = "<image>"
DEFAULT_IMAGE_PATCH_TOKEN = "<im_patch>"
DEFAULT_IMAGE_START_TOKEN = "<im_start>"
DEFAULT_IMAGE_END_TOKEN = "<im_end>"
DEFAULT_VIDEO_TOKEN = "<video>"
DEFAULT_VIDEO_PATCH_TOKEN = "<vi_patch>"
DEFAULT_VIDEO_START_TOKEN = "<vi_start>"
DEFAULT_VIDEO_END_TOKEN = "<vi_end>"
DEFAULT_SOUND_TOKEN = "<sound>"
DEFAULT_SOUND_PATCH_TOKEN = "<so_patch>"
DEFAULT_SOUND_START_TOKEN = "<so_start>"
DEFAULT_SOUND_END_TOKEN = "<so_end>"


